@startuml exclusion-rules
!theme plain

start
:Check date;

if (Is Saturday\nor Sunday?) then (yes)
    :Mark as\nweekend;
    :Exclude from\nrequirements;
    stop
endif

if (Is public\nholiday?) then (yes)
    :Mark as\nholiday;
    :Exclude from\nrequirements;
    stop
endif

if (Is vacation\nday?) then (yes)
    :Mark as\nvacation;
    :Exclude from\nrequirements;
    stop
endif

:Mark as\nworking day;
:Include in\nrequirements;
stop

@enduml

